Added support for window padding
snapappointments/bootstrap-select pull request #1503
Opened 2016-09-09 13:47 UTC by birjolaxew

As described in #1502.
Added an option called `windowPadding`, which supports the formats `x`, `"x x x x"` and `[x, x, x, x]`, where `x` is an integer. The string and array formats use the normal CSS order (top-right-bottom-left), while the number format applies to all sides.

[Fixed JSFiddle.](https://jsfiddle.net/9myc8ok9/)

Image comparisons:

<p align="center">
  <img align="top" src="https://cloud.githubusercontent.com/assets/4542461/18387599/bda6f9e6-769d-11e6-8b07-2ac30525df04.png" />
  <img align="top" src="https://cloud.githubusercontent.com/assets/4542461/18389126/ad76894a-76a4-11e6-956e-dd565d3d03a4.png" />
</p>

2016-09-12 20:32 UTC, birjolaxew commented
Updated to remove `dist/*` from commit so it can be merged without conflicts

2016-09-15 21:41 UTC, caseyjhol requested changes
Seems like a useful feature. I'm not sure we need to support the string option, though. Change it to support just a number or array of numbers using a simple `if (typeof winPad === 'number')` and I should be able to get this merged into the next version.

2016-09-16 06:15 UTC, birjolaxew commented
Done.

2016-09-16 18:38 UTC, caseyjhol approved these changes

2016-09-16 22:16 UTC, merged

2016-09-16 23:12 UTC, vsn4ik commented
It should be added in documentation.

2016-09-16 23:32 UTC, caseyjhol commented
Yes, I'll get it added before the official release.