Add placeholder option / deprecate title option (#2147)
snapappointments/bootstrap-select pull request #2369
Opened 2020-01-06 15:56 UTC by hndcrftd

Title option is deprecated (but still works for backwards compatibility). Placeholder option is now used.
'placeholder' can be set as html attribute, data attribute or set in the options object on init.
Updates to html attr or data attr will reflect upon calling refresh method.
Title, if set, is appended as title attribute on $button.
Title usage as placeholder can be removed by deleting line # 133.

2020-01-07 21:06 UTC, caseyjhol commented
Thanks for this! Reviewing. Would you mind changing this to the v1.14-dev branch instead? https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

2020-04-18 00:08 UTC, caseyjhol commented
With these changes, it's no longer possible to set the title programmatically.

v1.13.14: https://plnkr.co/edit/UBDl2ikH9aMwSq0l
5bb8f61: https://plnkr.co/edit/tfPLd02FWQJ3s3Qd

2020-04-18 00:10 UTC, caseyjhol requested changes
With these changes, it's no longer possible to set the title programmatically.

v1.13.14: https://plnkr.co/edit/UBDl2ikH9aMwSq0l
5bb8f61: https://plnkr.co/edit/tfPLd02FWQJ3s3Qd

2020-04-23 00:04 UTC, caseyjhol commented
Figured out the issue. Going to merge this and fix issues after.

2020-04-23 00:05 UTC, merged

2020-10-06 19:20 UTC, jrichview commented
It looks like I will need this. My organization is pushing back on it displaying title as the placeholder. They only want that to be a normal tooltip behavior.  I need to be able to set the placeholder to show the selected value or "-Select-" if nothing is selected.  The "noneSelectedText" is being set but it is being overridden by the title attribute.

Is this in a released version yet?