Fix #2659: Fix ajax search
snapappointments/bootstrap-select pull request #2710
Opened 2022-02-16 19:31 UTC by caseyjhol

- support passing in a boolean `more` argument as an additional argument to the callback function
- remove `source.load` method in favor of simply using `source.data`. `page` is now passed into `source.data` as the 2nd argument (just like `source.search`). If you want static data on init (and don't want to call your AJAX function), you can just check `page === 0`).

2022-02-16 19:33 UTC, caseyjhol commented
@NicolasCARPi This is still a WIP. I'll send it your way to review once I'm done.

2022-02-16 19:34 UTC, caseyjhol commented on js/bootstrap-select.js
> -      this.fetchData(function () {
removing this duplicate block

2022-02-17 00:17 UTC, caseyjhol commented
@NicolasCARPi I'm still working on fixes for #2671, but there's no reason those should hold up this fix. Let me know your thoughts on dropping the `source.load` method.

2022-02-17 12:49 UTC, NicolasCARPi requested changes
I think it would be best to have a test case in the `tests` folder, with a fake ajax call (just a function returning stuff), so we can actually assess if the fix works and have different test case (you said the bug wasn't found before because it was only triggered in certain conditions).

We don't have automated tests (yet), but I believe it's important to add test cases when possible.

2022-02-17 15:40 UTC, caseyjhol commented
@NicolasCARPi Have you made any progress on implementing Cypress? I also have Cypress experience and might try to tackle some of the initial groundwork if you haven't already.

2022-02-17 16:31 UTC, NicolasCARPi commented
Nope, I didn't, so feel free to lay the groundwork ;)

2022-03-17 10:51 UTC, NicolasCARPi approved these changes
I think it's great to finally have some end to end testing! This should be merged and a new beta version must be released ASAP :)

2022-03-17 14:24 UTC, merged

2022-03-17 23:18 UTC, caseyjhol commented
@NicolasCARPi Yes it's about time. I'm excited to add more. Going to make it so much easier to add new features and fix bugs. Just need to update the changelog and I think we can prep for a release. I'd like to also look into it to see if there's a way to automatically create a nuget release at the same time as well.

2022-03-18 00:22 UTC, NicolasCARPi commented
> create a nuget release

sure, see: https://github.com/marketplace/actions/publish-nuget

Keep in mind that github actions have issues right now ;) https://www.githubstatus.com/