[#2667]fix the bug of the data-size when the first option style has 'display: none'
snapappointments/bootstrap-select pull request #2713
Opened 2022-02-28 15:35 UTC by megumiimai

fix: #2667

2022-02-28 16:10 UTC, NicolasCARPi commented on js/bootstrap-select.js
> +          var a = data.element.firstChild;
`a` is a poor variable name choice

2022-03-01 14:07 UTC, NicolasCARPi requested changes
Thank you for your contribution. This change would be a good opportunity to add a test case in the `tests` folder (even if we don't currently test automatically for things yet). Basically an example showing the problem, and showing that with this PR the problem goes away!

2022-03-02 14:27 UTC, megumiimai commented
thank you for reviewing. I added a test and pasted the capture. How about that?

### problem
<img width="500" alt="スクリーンショット 2022-03-02 23 24 59" src="https://user-images.githubusercontent.com/26107262/156380508-bb8660bb-64c1-4abf-938f-972b18a74ad3.png">

### fixed
<img width="500" alt="スクリーンショット 2022-03-02 23 14 11" src="https://user-images.githubusercontent.com/26107262/156380043-26898e78-eba8-4686-b34d-07e3556a50d0.png">

2022-03-02 15:51 UTC, NicolasCARPi approved these changes
Thanks, looks good to me!

2022-03-02 15:52 UTC, merged